Fix ImportBevel for Blender 4.3
Fixes the error you get when attempting to import an object with Bevel Edges enabled.

The error AttributeError: 'MeshEdge' object has no attribute 'bevel_weight' is caused due to the Blender 4.3 changes to the Python API for bevel edges not being a property anymore but instead an attribute that only gets created if the user manually creates bevel weights in the model's edges in edit mode, and because the property doesn't exist then the import fails. https://developer.blender.org/docs/release_notes/4.0/python_api/

This updated ldraw_mesh.py fixes the issue by adding a "bevel_weight_edge" attribute to the created objects, that way the add-on can use this attribute instead of the deprecated one.

And because this is an API change that means the script with this version for the addon is only compatible with Blender 4.3 forwards